### ISSUE TITLE
Alternative Titles List for TV Shows

### ISSUE THREAD

**Issue by ishehadeh** [bcourtine/tmdb-client-rs#1]
tmdb-client always reads from the `"titles"` fields for `AlternativeTitlesList`, however, for tv shows, it should read from `"results"` instead.

Docs:
[get-tv-alternative-titles](https://developers.themoviedb.org/3/tv/get-tv-alternative-titles)
[get-movie-alternative-titles](https://developers.themoviedb.org/3/movies/get-movie-alternative-titles)

**Comment by bcourtine** [comment]
Thanks for reporting this. I will check and correct.

**Comment by bcourtine** [comment]
Hello @IanS5

Thanks for reporting the issue. I fixed it and published a new 1.5.4 release.
